name: Update sources

on:
  schedule:
    - cron:  '25,55 * * * *'
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.x'
    - name: Install packages
      run: |
        pip install altparse
    - name: Run python scripts
      run: |
        export GITHUB_TOKEN="${{ secrets.ACCESS_TOKEN }}"
        python update.py
    - name: Git add and commit
      uses: EndBug/add-and-commit@v9
      with:
        add: '--all'
        default_author: github_actions
